"""
gen_model_coefs.py
==================
Extrait les parametres du modele entraine (clf.pkl) et emet un
header C `eeg_model_params.h` pour le decodeur embarque.

Pipeline saved dans clf.pkl :
    make_pipeline(StandardScaler(),
                  OneVsRestClassifier(LogisticRegression()))

Sortie :
    scaler_mean      [EEG_N_FEATURES]                <- StandardScaler.mean_
    scaler_scale     [EEG_N_FEATURES]                <- StandardScaler.scale_
    model_coef       [EEG_N_CLASSES][EEG_N_FEATURES] <- LR.coef_[0] par estimator
    model_intercept  [EEG_N_CLASSES]                 <- LR.intercept_[0] par estimator
    class_names      [EEG_N_CLASSES]                 <- ovr.classes_ (str)

Usage :
    pip install joblib scikit-learn numpy        # une fois
    python gen_model_coefs.py
"""

import joblib
import numpy as np
from pathlib import Path

# ============ Chemins (ajuste si besoin) ============================
# Par defaut on suppose que ce script vit dans:
#   BMI-EMG-Firmware/test_folder/eeg_decoder_nucleo_wba65/tools/
# et que clf.pkl est dans:
#   BMI-EEG-Firmware/clf.pkl
# (4 niveaux au-dessus + BMI-EEG-Firmware/)
HERE     = Path(__file__).resolve().parent
PKL_PATH = HERE / "../../../../BMI-EEG-Firmware/clf.pkl"
OUT_PATH = HERE / "../Core/Inc/eeg_model_params.h"

# ============ Tailles attendues (doivent matcher eeg_features.h) =====
EXP_N_FEATURES = 100   # 20 channels x 5 bands
EXP_N_CLASSES  = 6


def main():
    pkl_path = PKL_PATH.resolve()
    out_path = OUT_PATH.resolve()
    print(f"Loading  : {pkl_path}")
    if not pkl_path.exists():
        raise FileNotFoundError(
            f"clf.pkl introuvable a {pkl_path}\n"
            f"-> Edite PKL_PATH en haut du script."
        )
    clf = joblib.load(pkl_path)

    # ---- Demonte le pipeline -----------------------------------------
    # make_pipeline cree des steps nommees automatiquement :
    #   'standardscaler' et 'onevsrestclassifier'
    try:
        scaler = clf.named_steps["standardscaler"]
        ovr    = clf.named_steps["onevsrestclassifier"]
    except (AttributeError, KeyError) as e:
        raise RuntimeError(
            f"clf.pkl ne ressemble pas a make_pipeline(SS, OVR(LR)).\n"
            f"  type(clf) = {type(clf)}\n"
            f"  Inspecte le pickle avant de relancer.\n"
            f"  (erreur originale: {e})"
        )

    # ---- StandardScaler ----------------------------------------------
    mean  = np.asarray(scaler.mean_,  dtype=np.float32)
    scale = np.asarray(scaler.scale_, dtype=np.float32)
    assert mean.shape  == (EXP_N_FEATURES,), f"mean shape {mean.shape}"
    assert scale.shape == (EXP_N_FEATURES,), f"scale shape {scale.shape}"

    # ---- OneVsRestClassifier : 6 LogisticRegression ------------------
    estimators = ovr.estimators_
    classes    = list(ovr.classes_)   # peut etre des ints ou des strs
    n_classes  = len(estimators)
    assert n_classes == EXP_N_CLASSES, (
        f"got {n_classes} classes, expected {EXP_N_CLASSES}"
    )

    coef      = np.zeros((n_classes, EXP_N_FEATURES), dtype=np.float32)
    intercept = np.zeros((n_classes,),                dtype=np.float32)
    for i, est in enumerate(estimators):
        assert est.coef_.shape == (1, EXP_N_FEATURES), (
            f"est[{i}].coef_ shape {est.coef_.shape}"
        )
        assert est.intercept_.shape == (1,), (
            f"est[{i}].intercept_ shape {est.intercept_.shape}"
        )
        coef[i]      = est.coef_[0]
        intercept[i] = est.intercept_[0]

    # ---- Sanity print -------------------------------------------------
    print(f"\nExtracted:")
    print(f"  scaler_mean      shape={mean.shape}  range=[{mean.min():+.3g}, {mean.max():+.3g}]")
    print(f"  scaler_scale     shape={scale.shape} range=[{scale.min():+.3g}, {scale.max():+.3g}]")
    print(f"  classes (n={n_classes}): {classes}")
    print(f"  model_coef       shape={coef.shape}  range=[{coef.min():+.3g}, {coef.max():+.3g}]")
    print(f"  model_intercept  values={intercept.tolist()}")

    # ---- Emit C header ------------------------------------------------
    lines = []
    a = lines.append
    a("/*")
    a(" * eeg_model_params.h  --  AUTO-GENERATED, DO NOT EDIT BY HAND.")
    a(" *")
    a(" * Generated by tools/gen_model_coefs.py from clf.pkl.")
    a(" * Pipeline: StandardScaler -> OneVsRestClassifier(LogisticRegression).")
    a(" *")
    a(f" * Source: {pkl_path}")
    a(" */")
    a("")
    a("#ifndef EEG_MODEL_PARAMS_H")
    a("#define EEG_MODEL_PARAMS_H")
    a("")
    a('#include "eeg_features.h"')
    a("")

    def emit_1d(name, arr, per_line=6):
        a(f"static const float {name}[{arr.shape[0]}] = {{")
        for i in range(0, len(arr), per_line):
            chunk = arr[i:i+per_line]
            row = ", ".join(f"{v:+.10e}f" for v in chunk)
            a("    " + row + ",")
        a("};")
        a("")

    def emit_2d(name, arr, per_line=6):
        rows, cols = arr.shape
        a(f"static const float {name}[{rows}][{cols}] = {{")
        for r in range(rows):
            a(f"    /* class {r}: {classes[r]} */")
            a("    {")
            for i in range(0, cols, per_line):
                chunk = arr[r, i:i+per_line]
                row = ", ".join(f"{v:+.10e}f" for v in chunk)
                a("        " + row + ",")
            a("    },")
        a("};")
        a("")

    emit_1d("scaler_mean",     mean)
    emit_1d("scaler_scale",    scale)
    emit_2d("model_coef",      coef)
    emit_1d("model_intercept", intercept)

    a("/* Human-readable class labels (handy for printf) */")
    a("static const char *const class_names[EEG_N_CLASSES] = {")
    for c in classes:
        a(f'    "{c}",')
    a("};")
    a("")
    a("#endif /* EEG_MODEL_PARAMS_H */")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\nWrote {out_path}")
    print(f"  {len(lines)} lines")


if __name__ == "__main__":
    main()